### ISSUE TITLE
Error with server.js

### ISSUE THREAD

**Issue by dubloch** [NearW/minecraft-speedrun#10]
![Bild_2021-07-21_141133](https://user-images.githubusercontent.com/87762298/126486420-d34354c6-ff44-4dc7-acb5-eaf0095401cf.png)

How can I fix that?

**Comment by NearW** [comment]
The files
- server.js
- start.sh
- speedrun.json

must be within the same directory.

Also make sure to execute the shell script from that directory as well.

If this didn't help, it would be great if you could provide a screenshot of your files within that folder.

**Comment by dubloch** [comment]
![Bild_2021-07-21_153229](https://user-images.githubusercontent.com/87762298/126497141-f1dd38df-7ac9-43c0-a494-37ca6aefab14.png)

I'm starting the Start.sh with "sudo ./Start.sh"

I also gave those files +x rights. But it still doesn't work.

**Comment by NearW** [comment]
That's super weird.

You can also simply open the terminal and run `node server.js` to start the script. 

I'll try to look into this asap and I hope this workaround does thr trick for you for now.

**Comment by dubloch** [comment]
The workaround did work. Thanks! :D 
Still weird why I can start it like that but not with Start.sh.
Still thanks for your fast help. :)

**Comment by NearW** [comment]
Perfect. The code inside the shell-script doesn't work on your operating system. I'd love to fix that.

What operating system and which distribution are you using?

GL running! o/

**Comment by dubloch** [comment]
I'm using a VPS with Ubuntu 20.04.

**Comment by NearW** [comment]
@dubloch 

Can you try executing `sh ./Start.sh` instead?

**Comment by dubloch** [comment]
![Bild_2021-07-25_162446](https://user-images.githubusercontent.com/87762298/126902581-85748fdd-3549-4aca-9b09-6970ecde3b21.png)

Still the same error

**Comment by NearW** [comment]
One last try before I'll get my own ubuntu instance running to fix this issue:

https://github.com/NearW/minecraft-speedrun/releases/tag/1.4.1
Try this `Start.sh` file and execute it like this `./Start.sh`

**Comment by dubloch** [comment]
It works now. Thank you so much. Started it with sudo ./Start.sh
You are a great guy, keep the work up. :D
