### ISSUE TITLE
Any way to reset world without /exit first?

### ISSUE THREAD

**Issue by Wajiddat18c** [NearW/minecraft-speedrun#13]
Hi, does a command exist that resets the world without having to close close the server down relaunch and the Start.bat file?

**Comment by NearW** [comment]
The only way to generate a new world is to stop the server. The script will automatically restart the server once it was stopped.

Therefore typing `/stop` in the chat will automatically restart the server.

Does that answer your question?

**Comment by Wajiddat18c** [comment]
Yeah thanks!

tor. 30. mar. 2023 08.14 skrev Ben Willenbring ***@***.***>:
