### ISSUE TITLE
Map wont restart afer stop

### ISSUE THREAD

**Issue by Lulciano** [NearW/minecraft-speedrun#14]
Pls help, I am trying to set this whole thing but im kinda new on this, I managed to get the server working but when I stop it and  start it again, it doesnt reset it just keeps the same world.

#Minecraft server properties
#Wed Apr 19 04:13:23 EDT 2023
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings=
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=true
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
server-ip=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
resource-pack=
entity-broadcast-range-percentage=100
rcon.password=
player-idle-timeout=0
force-gamemode=false
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
snooper-enabled=true
function-permission-level=2
level-type=default
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=0
max-world-size=29999984

"MIN_RAM": 8,
	"MAX_RAM": 10,
	"OP": ["Notch"],
	"WHITELIST": ["Notch"],
	"DATA_PACK": false,
	"SEEDS": ["-9223372036854775808", "9223372036854775807"],
	"AUTO_SAVE": false,
	"KEEP_WORLDS": false,
	"LOAD_WORLD": "",
	"JAR_NAME": "server.jar"

**Comment by NearW** [comment]
Hi @Lulciano 

I think you're not executing the script correctly, since you said something about "starting and stopping the server".

The script takes care of that for you. You simply run the server by executing the .sh or .bat file provided. You can then type /stop into the chat to restart the server.
