### ISSUE TITLE
Issue Logging into Server

### ISSUE THREAD

**Issue by timothyihaynes** [NearW/minecraft-speedrun#2]
When I run the .bat file the js script runs (i.e. my world get's deleted), but the server isn't starting. I've checked all the basic stuff (correct file configuration, JRE version, etc.), but those don't seem to be causing the issue; in fact, if I run the .jar file in my root directory then the vanilla 1.16.1 server runs fine. Am I just doing something wrong?

![root dir](https://user-images.githubusercontent.com/71913278/112223621-3149c300-8bf8-11eb-9e7c-82e917df5f78.PNG)
![speedrun json](https://user-images.githubusercontent.com/71913278/112223686-40307580-8bf8-11eb-9a4b-9e112428a217.PNG)

**Comment by NearW** [comment]
I assume that the terminal simply closes after running the script by executing the bat-file.

Can you run the server.js directly using node? Just type _node server.js_ in the terminal.

I'd be interested in the console output.

**Comment by timothyihaynes** [comment]
It seems like when I run the command using node the program is just getting stuck, as I am not receiving any output from the terminal.
![image](https://user-images.githubusercontent.com/71913278/112502629-39207900-8d58-11eb-8c75-7924cb060eae.png)
As you can see, I've run the command (it may look like I haven't but that is just due to no output), yet their is no terminal output indicating that the server has started, and when I try to login to the server it gives me a similar error message to when I try and join a vanilla server without executing the respective .jar file.

**Comment by NearW** [comment]
It's hard to tell what the problem is here, since the script itself has no proper feedback besides propagating the console output from the jar itself.

I'll release another version with some better logging tomorrow. Maybe this will help to debug your issue. I'd love to get this fixed.

Can you give me some more details on your OS, node version and java version?

**Comment by timothyihaynes** [comment]
Ok, I currently have Node.js v14.16.0 installed. As for my Java version, I am currently using a jdk (version 13.0.2), but I have also tried  running the server with my jre (version 1.8_281) which gave similar results. Lastly, the OS on my computer is Windows 10 Home (version 20H2; build 19042.867). Hopefully this new update will give us some new information!

**Comment by timothyihaynes** [comment]
Turns out that there was an issue with one of my .json files when I initially tested with my 1.8 jre. After I fixed it and changed my java version, the server seems to be working fine. Thanks for the help, if you hadn't reminded me about the java version I probably wouldn't have figured it out!
