### ISSUE TITLE
Minecraft Hoster

### ISSUE THREAD

**Issue by Nikita-Philippe** [NearW/minecraft-speedrun#3]
Hi everyone, 

I setup the script but i cant make it work, when i /stop the server is just restarting. I think the problem is that i'm on a server hoster (MelonCube) so i can't run the Start.bat.
Do you have an idea how can i make it work ?

Thanks

**Comment by NearW** [comment]
This script should not be used on a normal SMP world. It's supposed to restart the server when it would usually simply stop.

This allows the speedrunners to simply stop the server to generate a new world.

You can create a .bat file with the following code to run it normally:

java -Xms2G -Xmx4G -jar server.jar nogui

where -Xms and -Xmx specify the minimum and maximum RAM.

https://medium.com/swlh/how-to-make-a-minecraft-server-the-2020-guide-2e1ca5f8b7c1

**Comment by Nikita-Philippe** [comment]
Ok, thanks.
So as i understand it, it's not possible to use this script on a minecraft server hoster like mine, i should host the server myself to allow me to run bat file ?

**Comment by Nikita-Philippe** [comment]
I create my server on my computer, and everything works perfectly fine.
