### ISSUE TITLE
Add Enable Autosave Support

### ISSUE THREAD

**Issue by Civitello** [NearW/minecraft-speedrun#4]
I would like it to be possible to enable autosave. We require this as we are doing AA and the runs last hours.

**Comment by NearW** [comment]
Accepted. Will be added soon.

**Comment by NearW** [comment]
https://github.com/NearW/minecraft-speedrun/commit/05a5d60644157b408e7bf773338cd8a4af0390c4

Release will be tonight or tomorrow.
