### ISSUE TITLE
Add rename world instead of delete

### ISSUE THREAD

**Issue by Civitello** [NearW/minecraft-speedrun#5]
speedrun.com moderators sometimes request worlds that were reset to be saved. Renaming worlds instead of deeting would make this work.

**Comment by NearW** [comment]
Accepted. Will be added soon.

**Comment by NearW** [comment]
https://github.com/NearW/minecraft-speedrun/commit/91e08b58d5bdf4662935066f8b223ad93701e6bf

Release will be tonight or tomorrow.
