### ISSUE TITLE
server.js doesn't work?

### ISSUE THREAD

**Issue by ArchieDxncan** [NearW/minecraft-speedrun#8]
when i run start.bat, it comes up with:
C:\Users\archi\Downloads\Co-Op Speedrun>node server.js
Parsing speedrun.json ...
SyntaxError: Unexpected string in JSON at position 121
    at JSON.parse (<anonymous>)
    at C:\Users\archi\Downloads\Co-Op Speedrun\server.js:1:68523
    at Generator.next (<anonymous>)
    at s (C:\Users\archi\Downloads\Co-Op Speedrun\server.js:1:67108)

What can i do to fix it?

**Comment by NearW** [comment]
The error implies, that your speedrun.json is not written correctly.

Either google how the json format works or paste your speedrun.json below and I'll spot your small error! :)
or validate your json [here](https://jsonlint.com/)

**Comment by ArchieDxncan** [comment]
{
	"MIN_RAM": 8,
	"MAX_RAM": 10,
	"OP": ["MiniDuncan"],
	"WHITELIST": ["MiniDuncan"],
	"DATA_PACK": false,
	"SEEDS": []
	"AUTO_SAVE": false,
	"KEEP_WORLDS": true,
	"LOAD_WORLD": "world"
}

**Comment by NearW** [comment]
Missing `, ` after `"SEEDS": []`.

Correct:
```json
{
	"MIN_RAM": 8,
	"MAX_RAM": 10,
	"OP": ["MiniDuncan"],
	"WHITELIST": ["MiniDuncan"],
	"DATA_PACK": false,
	"SEEDS": [],
	"AUTO_SAVE": false,
	"KEEP_WORLDS": true,
	"LOAD_WORLD": "world"
}
```
